- Gemfile.lock
- app/models/medication.rb
- db/migrate/20230306223545_create_medications.rb
- db/schema.rb
- test/models/medication_test.rb
-medication model created
-no controller since no need for one
@adhamkou please check and merge when done
> Create medication model controller

- Gemfile.lock
- app/models/allergy.rb
- db/migrate/20230307011740_create_allergies.rb
- db/schema.rb
- test/models/allergy_test.rb
> added an allergy model

- Gemfile.lock
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_cardcategory.scss
- app/assets/stylesheets/components/_cardproduct.scss
- app/assets/stylesheets/components/_cardtrip.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_notification.scss
- app/assets/stylesheets/components/_searchform.scss
- db/schema.rb
> Adding scss components

- db/migrate/20230307170745_change_type_name_in_allergies.rb
- db/schema.rb
- db/seeds.rb
seeded medications and allergies
> User medications model controller

- app/controllers/user_medications_controller.rb
- app/models/user.rb
- app/models/user_medication.rb
- app/views/user_medications/my_medications.html.erb
- config/routes.rb
- db/migrate/20230307163505_create_user_medications.rb
- db/schema.rb
- test/controllers/user_medications_controller_test.rb
- test/models/user_medication_test.rb
- created a UserMedication model
- added get '/my_medications', to: 'user_medications#my_medications' to routes.rb
- added has_many :user_medications to user.rb
- created a my_medications action in user_medications controller
- created a my_medications.html.erb
- added html in my_medications.html.erb to show user_medications medication name
@adhamkou please check and merge when all good
> Create user medication model

- app/controllers/orders_controller.rb
- app/models/order.rb
- app/views/orders/show.html.erb
- config/routes.rb
- db/migrate/20230307185404_create_orders.rb
- db/schema.rb
- test/controllers/orders_controller_test.rb
- test/models/order_test.rb
- added resources :order, only: %i[new create show] in routes.rb
- generated an order model with user_medication:references
- generated an orders controller 
- created a show action in controller
- created show.html.erb
@adhamkou please check and merge when all good
> created order model and controller

- app/models/user.rb
- db/migrate/20230307190127_add_first_name_to_users.rb
- db/migrate/20230307191733_add_last_name_to_users.rb
- db/migrate/20230307192351_add_birthdate_to_users.rb
- db/migrate/20230307194541_add_address_to_users.rb
- db/migrate/20230307194817_add_phone_number_to_users.rb
- db/migrate/20230307195018_add_pharmacy_location_to_users.rb
- db/migrate/20230307195342_change_pharmacy_location_to_users.rb
- db/schema.rb
@CloneProtocolSixtySix  : i add all the columns to the table users
> Add columns to table users

- app/models/order.rb
- app/models/user.rb
- app/views/orders/show.html.erb
- db/migrate/20230307201345_change_reference_in_orders.rb
- db/migrate/20230307201811_add_user_medication_reference_to_refills.rb
- db/schema.rb
- changed the schema 
- added user_id to orders table and took off user_medications_id 
- added user_medication_id to refills table
- added **has_many :user_medications, through: :refills** and **belongs_to :user** to order.rb
- added **has_many :user_medications, :orders** to user.rb
@adhamkou please double check and merge when ok
> Make changed the schema

- app/models/user.rb
- db/schema.rb
- put has_many :orders on another line in the user.rb
> fixed associations in user model

- app/controllers/profiles_controller.rb
- test/controllers/profiles_controller_test.rb
@adhamkou   : adding controller profiles and action "dashboard"
> finish adding profiles controller and dashboard action

- app/models/refill.rb
- app/models/user.rb
- app/models/user_medication.rb
- db/seeds.rb
added seeds
fixed association between user-med and refills
@youpancan
> added seeds and fixed some associations

- app/views/orders/show.html.erb
- config/routes.rb
- added content to order show page(now shows medication name and status of refill)
> Create show for orders

- app/controllers/application_controller.rb
- app/controllers/profiles_controller.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- app/views/profiles/dashboard.html.erb
- config/routes.rb
@adhamkou : add the view for profiles
> finish adding the view to profiles

- db/seeds.rb
@adhamkou  reorder the destroy queue.
> Change order of delete statements in seeds

- app/views/devise/registrations/new.html.erb
@CloneProtocolSixtySix  the calender year can be select from 90 years to  few monthes old
> fix-calendar-in-login

- app/assets/stylesheets/components/_flataccordion.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
> added a navbar

- app/controllers/profiles_controller.rb
- app/views/profiles/dashboard.html.erb
- app/views/shared/_medication_card.html.erb
@CloneProtocolSixtySix  add the correct data to the profile page
> Display current user and active medication on profile

- app/assets/stylesheets/components/_avatar.scss
- app/views/shared/_navbar.html.erb
> navbar avatar update

- app/controllers/orders_controller.rb
- app/views/orders/index.html.erb
- app/views/shared/_navbar.html.erb
- app/views/user_medications/my_medications.html.erb
- config/routes.rb
- added index for order in routes
- added the index action  in the orders controller
- created an index.html.erb in order views
- added the code to display all orders id
- made displayed IDs clickable, linking to the show page of said order.
> Added order index

- app/views/user_medications/my_medications.html.erb
- added the code to display all the details of the user_medication in my_medications.html.erb
@adhamkou please check and merge please
> added the details for the user_med in my_medications.html.erb

- app/views/orders/index.html.erb
- app/views/orders/show.html.erb
- app/views/profiles/dashboard.html.erb
- app/views/shared/_medication_card.html.erb
- app/views/user_medications/my_medications.html.erb
- added a few divs to separate info properly 
- added margin top to container divs
- added <strong> to info
> added divs to pages

- app/views/orders/show.html.erb
-just put the div into the bloc instead of outside the bloc
> fixed a div

- app/controllers/profiles_controller.rb
- app/models/user.rb
- app/views/profiles/dashboard.html.erb
- app/views/profiles/edit.html.erb
- app/views/shared/_edit-form.html.erb
- config/routes.rb
@youpancan 
edit and patch added to profile controller
> edit and patch profile

- app/controllers/notifications_controller.rb
- app/models/notification.rb
- app/models/user_medication.rb
- db/migrate/20230308202000_create_notifications.rb
- db/schema.rb
- test/controllers/notifications_controller_test.rb
- test/models/notification_test.rb
@adhamkou  added notifications model and controller
> Create notifications model and controller

- db/seeds.rb
> added a pending order

- app/views/orders/index.html.erb
> changed the divs place to display orders correctly

- app/models/user_medication.rb
> updated user_medications model

- app/controllers/profiles_controller.rb
- app/views/profiles/edit.html.erb
- app/views/profiles/show.html.erb
- app/views/shared/_edit-form.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- added '/dashboard/show', to: 'profiles#show' in routes.rb
- added a show action in profiles controller
- added a show view which displays user info
- added a button link to edit profile
- added Personal information link in hamburger dropdown in nav
- made it so that RX buddy in nav brings back to dashboard
@adhamkou please check and merge when good
> did a few changes

- app/controllers/notifications_controller.rb
- app/views/notifications/show.html.erb
@maggiehum   notification page finish builded when order is ready
> display-notification-on-order-ready finish

- app/views/pages/home.html.erb
> fixed footer in the home page

- app/assets/stylesheets/components/_home.scss
- app/views/pages/home.html.erb
- app/views/shared/_footer.html.erb
> made buttons pink

- app/assets/stylesheets/components/_home.scss
- app/views/profiles/show.html.erb
- app/views/shared/_navbar.html.erb
- changed RX-Buddy in nav to white
- added a little bit of bootstrap padding, margin and border ton personal info page
-  changed the background colour to all our pages to the colour decided in figma
- changed the order of the links in our hamburger drop down
> changed background color

- app/models/user_medication.rb
- app/views/shared/_medication_card.html.erb
@adhamkou  disactive button for refill if not match condiction
> disactive button refill if not match condition

- app/assets/stylesheets/components/_cardmed.scss
- app/assets/stylesheets/components/_index.scss
-added box shadow to medication cards
> added box shaddow to med cards

- app/views/user_medications/my_medications.html.erb
- fixed days until next refill instead of days since your last refill
> fixed days until next refill

- app/views/shared/_medication_card.html.erb
- app/views/shared/_navbar.html.erb
- added Dashboard link back in hamburger drop down
- moved the Personal Info link in avatar drop down 
- added the days until next refill to medication_card partial 
> fixed the links in nav

- app/controllers/profiles_controller.rb
- app/views/profiles/dashboard.html.erb
- db/migrate/20230309191503_add_coordinates_to_users.rb
- db/seeds.rb
- there was a migration issue that i fixed (db:migrate and reset weren't working)
- fixed the seed issue (we created the same users twice, so i kept the one with a real address for the map to work later)
- fixed the end
- created a border around where the map is supposed to be but the map is not showing for now
- fixed the dashboard first and last name in html file
@maggiehum
> fixed the end in profiles controller and fixed the seeds and migration

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_home.scss
- app/assets/stylesheets/components/_navbar.scss
- app/javascript/controllers/index.js
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
> made nav sticky

- app/javascript/controllers/map_controller.js
- app/models/user.rb
- app/views/profiles/dashboard.html.erb
- db/schema.rb
- db/seeds.rb
> map markers set for pharma

- app/controllers/orders_controller.rb
- app/javascript/controllers/index.js
- app/javascript/controllers/notice_confirmation_controller.js
- app/views/shared/_flashes.html.erb
- db/schema.rb
- created a 'Thank you for your order.' alert notice 
- created a stimulus controller to have a timeout for the notice to disappear.
> created a thank you notice with timeout

- app/controllers/orders_controller.rb
- app/views/orders/index.html.erb
- app/views/orders/show.html.erb
- db/migrate/20230310195511_add_order_date_to_orders.rb
- db/schema.rb
- db/seeds.rb
- added an order_date column to the orders table
- added dates to order.create! in seeds.rb
- changed the view so that you can see the date the order was placed
- aligned everything in the cards in the order history view
- added the chevron icon to indicate that when you press on the card you can see details of order
> fixed the order hisotry page

- app/models/user.rb
- db/migrate/20230310210854_add_coordinates_to_users.rb
- db/schema.rb
Recreated missing migration preventing the `Geocoder` gem from working on Heroku
> Added migration for coords in users

- app/views/orders/index.html.erb
> reverse chronological for orders index

- app/javascript/controllers/map_controller.js
> changing map color

- app/assets/stylesheets/pages/_dashboard.scss
- app/views/orders/show.html.erb
- app/views/profiles/dashboard.html.erb
- app/views/shared/_medication_card.html.erb
- centered Steps until pickup with the icons in the dashboard dropdown med cards
- took margins off from the pharmacy name and active medications in dashboard
> aligned steps until pickup

- app/views/profiles/dashboard.html.erb
> changed map border color

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_dashboard.scss
> Fancy buttons

- app/assets/stylesheets/pages/_dashboard.scss
- app/views/pages/home.html.erb
- app/views/refills/review.html.erb
> images on heroku

- app/assets/stylesheets/components/_status.scss
- app/models/refill.rb
- app/views/shared/_medication_card.html.erb
- db/migrate/20230313200731_add_default_value_to_pick_up_date.rb
- db/schema.rb
- db/seeds.rb
> add steps when you request a refill and order in dashboard

- app/views/shared/_medication_card.html.erb
> fixed number refills

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_status.scss
- app/controllers/profiles_controller.rb
- app/javascript/controllers/index.js
- app/javascript/controllers/tom_select_controller.js
- app/models/user.rb
- app/views/layouts/application.html.erb
- app/views/profiles/edit.html.erb
- app/views/profiles/show.html.erb
- app/views/shared/_edit-form.html.erb
- package.json
- yarn.lock
- added a drop down bow to show allergies in the Personal Info page
- added the tom-select in the form to edit personal info
- still need to stylize
> Adding allergies to form

- app/assets/stylesheets/components/_index.scss
- app/views/shared/_medication_card.html.erb
> added green border when selected for refill

- lib/tasks/rx.rake
> initial scripts

- app/models/user_medication.rb
- app/views/orders/show.html.erb
@Ayatamin25 
- made button unclickable when there is a refill in process
- added a pending icon
> Fix order status page

- app/assets/stylesheets/components/_allergy.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/pages_controller.rb
- app/javascript/controllers/tom_select_controller.js
- app/views/profiles/show.html.erb
- app/views/shared/_edit-form.html.erb
- changed the size of My Allergies in the drop down button of personal information page
- changed the tag colour to one from our palette in the Edit page of personal info for allergies
- added the remove button next to the tags in the edit info
> added the remove button to the allergy tom-select

- app/assets/stylesheets/pages/_dashboard.scss
- app/views/profiles/dashboard.html.erb
> adjusted squiggly

- app/assets/stylesheets/components/_date.scss
- app/views/orders/show.html.erb
- changed id of order_date from #date to #order_date so that it doesnt influence the birthdate font in edit personal info
> changed the birthdate font in edit info

- app/models/refill.rb
- app/views/shared/_medication_card.html.erb
- created a method that updates status of refill, refill due date and number refills for user-med
@Ayatamin25
> Update refill due date and refills amount

- app/views/orders/show.html.erb
> add back button in orders show page

- app/views/shared/_medication_card.html.erb
> removed button when not refillable

- app/assets/stylesheets/components/_header.scss
- app/assets/stylesheets/components/_home.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/views/orders/index.html.erb
- app/views/orders/show.html.erb
- app/views/pages/home.html.erb
- app/views/profiles/dashboard.html.erb
- app/views/profiles/edit.html.erb
- app/views/profiles/show.html.erb
- app/views/refills/review.html.erb
- app/views/shared/_navbar.html.erb
- app/views/user_medications/my_medications.html.erb
@maggiehum  I updated the home page
> Home page new

- db/schema.rb
- db/seeds.rb
> add seeds for chatbot sarah

- app/views/profiles/show.html.erb
@maggiehum  add one 'Back' button on the page edit personal information
> finish adding the button to profile edit

- app/assets/stylesheets/components/_home.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- db/schema.rb
updated home page icons  @adhamkou
> Resolve problem

- app/assets/stylesheets/pages/_dashboard.scss
- app/views/orders/index.html.erb
- app/views/pages/home.html.erb
- app/views/profiles/dashboard.html.erb
- app/views/profiles/edit.html.erb
- app/views/profiles/show.html.erb
- app/views/refills/review.html.erb
- app/views/user_medications/my_medications.html.erb
@maggiehum adjusted some margins
> home-changes

- app/controllers/messages_controller.rb
- app/jobs/chatbot_answer_job.rb
- config/cable.yml
- config/routes.rb
- config/sidekiq.yml
- db/schema.rb
> fixing bugs

- app/assets/stylesheets/components/_home.scss
- app/views/pages/home.html.erb
@adhamkou fixed home page margins
> updated home page margins

- app/controllers/notifications_controller.rb
- config/cable.yml
- reenabled notifications controller class 
> Fix zeitwerk

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
@Ayatamin25  change the logo to title text
> finish changing from logo to title-text

- app/views/user_medications/my_medications.html.erb
> fixed logic in my medications history

- app/assets/stylesheets/components/_alert.scss
> Fix notice

- app/controllers/profiles_controller.rb
- app/views/profiles/dashboard.html.erb
- app/views/shared/_allergy.html.erb
- app/views/shared/_medication_card.html.erb
- db/seeds.rb
- You can see 'You are allergic to this medication on the med card that you are allergic to 
- We now need to make sure that the refill button does not show when allergy is present
> allergy logic is there just need to remove button

- app/controllers/orders_controller.rb
- app/views/orders/show.html.erb
@Ayatamin25  remove tag "<" and redirect to orders page after submit order
> remove tag and redirect to order status after submit order'

- app/views/layouts/application.html.erb
- app/views/orders/index.html.erb
- app/views/orders/show.html.erb
- app/views/profiles/dashboard.html.erb
- app/views/user_medications/my_medications.html.erb
@Ayatamin25 remove chatbot icon on three pages
> chatbot remove on home page,chat page, personal information page

- app/assets/stylesheets/components/_buttonhome.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_home.scss
- app/assets/stylesheets/components/_index.scss
- app/views/pages/home.html.erb
> Final styles

- app/views/shared/_allergy.html.erb
- app/views/shared/_medication_card.html.erb
> medication card updated to show message when allergic to med

- app/assets/stylesheets/components/_buttonhome.scss
- app/assets/stylesheets/components/_notification_bell.scss
- app/views/shared/_allergy.html.erb
> Fix allergy warning

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/_notification_bell.scss
- app/javascript/controllers/user_subscription_controller.js
- app/views/shared/_navbar.html.erb
- lib/tasks/rx.rake
- made the notif drop down pink with low opacity
- centered the text
- added an X to close drop down
- the avatar dropdown is messed up. Have to fix.
- moved the navbar items around to center the rxbuddy
> stylized the notification dropdown

- app/assets/stylesheets/components/_notification_bell.scss
- made the notif dropdown box more opaque
@CloneProtocolSixtySix please check and merge :)
> changed the opacity of the notif box

- app/assets/stylesheets/components/_allergy.scss
- fixed a font in the drop down for allergies 
@CloneProtocolSixtySix please check and merge
> fixed the allergy font

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
-made the avatar a link to edit info
-added log out button in burger
@maggiehum
> Avatar info logout

- app/assets/stylesheets/components/_chatbot.scss
- app/views/shared/_allergy.html.erb
- app/views/shared/_chat.erb
- fixed the chat icon position to sticky so that it does not overlap the footer
> fixed the chat icon position

- app/assets/stylesheets/components/_cardmed.scss
- app/assets/stylesheets/components/_chatbot.scss
- app/views/shared/_chat.erb
- put a div around the chat button so that the whole line isnt clickable just the icon
> fixed problem with chat icon

- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_cardmed.scss
- app/assets/stylesheets/components/_date.scss
- app/assets/stylesheets/components/_urgency.scss
- app/views/orders/index.html.erb
- app/views/orders/show.html.erb
- app/views/refills/review.html.erb
- app/views/shared/_navbar.html.erb
- Aligned the date in order show page 
- Added a Review your Order H1 in refill review
- Changed the send order and cancel order btn in refill review to our green and red 
- Removed the chat icon from the order show page
- changed the font size, font colour and font on the med cards in the order history and order status page so matches the dashboard cards
- changed the pending logo to grey instead of green
> fixed date alignment & btn colours

- app/assets/stylesheets/components/_allergy.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_personal.scss
- app/assets/stylesheets/config/_fonts.scss
- app/views/profiles/show.html.erb
- db/seeds.rb
- Changed the font in personal info 
- added a little bit of bottom margin to the button so that they arent stuck to the footer
- switched the buttons sides. back is on left and edit on right
> Fix font personal info

- app/jobs/chatbot_answer_job.rb
> new message

- app/assets/stylesheets/components/_chatbot.scss
- app/jobs/chatbot_answer_job.rb
- app/views/chatbots/show.html.erb
- app/views/messages/_auto_message.html.erb
- made the automatic message for chatbot
@Ayatamin25 check and merge please
> Chatbot new message

- app/views/pages/home.html.erb
> tweaked home page

- app/assets/stylesheets/components/_message.scss
- app/views/chatbots/show.html.erb
- app/views/messages/_auto_message.html.erb
- app/views/messages/_message.html.erb
> chat changes

- app/assets/stylesheets/components/_chatbot.scss
- app/views/messages/_auto_message.html.erb
> fix typewriter

- db/seeds.rb
-fixed seed to fit pitch
@youpancan please check and merge
> changed the seed

- app/models/refill.rb
- db/seeds.rb
- lib/tasks/rx.rake
- added a new method in refill model to put in process and change number of refills
- added that method in the in_process_urgent rx rake file so it can update it when run
- changed the seeds to add mroe number of refills
@maggiehum
> changed seeds and rx rake

- app/assets/stylesheets/components/_header.scss
- app/assets/stylesheets/components/_home.scss
- app/views/pages/home.html.erb
> centered for responsive page
